### ISSUE TITLE
 error: no field or member function named 'standardOptimizeOption' in 'build.Builder'

### ISSUE THREAD

**Issue by juleshenry** [adam-r-kowalski/atom#80]
**BUG**

**{
zig : 0.10.1,
macOS: "Ventura 13.4"
}** 

cannot find standardOptimizeOption.

Sequence failing was : 

```brew install zig```

```zig build test````

/Users/~/Desktop/extra/praying/mantis/build.zig:39:23: error: no field or member function named 'standardOptimizeOption' in 'build.Builder'
    const optimize = b.standardOptimizeOption(.{});
                     ~^~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/build.zig:31:21: note: struct declared here
pub const Builder = struct {
                    ^~~~~~
referenced by:
    runBuild: /opt/homebrew/Cellar/zig/0.10.1/lib/zig/build_runner.zig:232:22
    usage__anon_4534: /opt/homebrew/Cellar/zig/0.10.1/lib/zig/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

**Comment by adam-r-kowalski** [comment]
Thanks for reporting this! This is because `zig` changed their build system in version `0.11.0`. The specific version I am using is `0.11.0-dev.3258+7621e5693`. I recommend grabbing a binary from [here](https://ziglang.org/download/) until `brew` catches up

**Comment by adam-r-kowalski** [comment]
Closed based on the answer above. Please reopen if the problem persists with the latest version.
