### ISSUE TITLE
Break apart documentation into current and planned features

### ISSUE THREAD

**Issue by adam-r-kowalski** [adam-r-kowalski/atom#89]
Currently the README contains all the features of the language as well as proposed features that I wish to add. This makes it tricky to know which can currently be done with the compiler. I need to break apart the README into documentation for the language, as well as a series of proposals for planned features. It should still be possible to have a single document which you can paste as context for a LLM to prime it for help with language features.

**Comment by juleshenry** [comment]
could be trendy new langchain script solves this.

**Comment by adam-r-kowalski** [comment]
I'm going to revisit this in a little bit, but it is closed for now. I'm actually planning on removing all unsupported language features from the documentation and instead have them be rfcs and individual issues on the repo.
